export const LOAD_DRIVER_MATCHES = "LOAD_DRIVER_MATCHES";
export const LOAD_OWNER_MATCHES = "LOAD_OWNER_MATCHES";
export const MAKE_MATCH = "MAKE_MATCH";
export const LOAD_DRIVERS_INFO = "LOAD_DRIVER_INFO";
export const LOAD_OWNERS_INFO = "LOAD_OWNER_INFO";
export const MATCH_ERROR = "MATCH_ERROR";
