export const FETCH_CONNECTION_STARTED = "FETCH_CONNECTION_STARTED";
export const FETCH_CONNECTION_SUCCESS = "FETCH_CONNECTION_SUCCESS";
export const FETCH_CONNECTION_FAILURE = "FETCH_CONNECTION_FAILURE";
export const UPDATE_CONNECTION_STATUS_STARTED =
  "UPDATE_CONNECTION_STATUS_STARTED";
export const UPDATE_CONNECTION_STATUS_SUCCESS =
  "UPDATE_CONNECTION_STATUS_SUCCESS";
export const UPDATE_CONNECTION_STATUS_FAILURE =
  "UPDATE_CONNECTION_STATUS_FAILURE";
