// Add action types here

export const SAVE_VEHICLE_STARTED = 'SAVE_VEHICLE_STARTED';
export const SAVE_VEHICLE_SUCCESS = 'SAVE_VEHICLE_SUCCESS';
export const SAVE_VEHICLE_FAILURE = 'SAVE_VEHICLE_FAILURE';
export const LOAD_VEHICLES_SUCCESS = 'LOAD_VEHICLE_SUCCESS';
export const LOAD_VEHICLES_STARTED = 'LOAD_VEHICLES_STARTED';
export const LOAD_VEHICLES_FAILURE = 'LOAD_VEHICLES_FAILURE';
export const SAVE_LICENSE_SUCCESS = 'SAVE_LICENSE_SUCCESS';
export const SAVE_LICENSE_STARTED = 'SAVE_LICENSE_STARTED';
export const SAVE_LICENSE_FAILURE = 'SAVE_LICENSE_FAILURE';
