export const LOAD_DATABASE_LIST_SUCCESS = 'LOAD_DATABASE_LIST_SUCCESS';
export const LOAD_DATABASE_LIST_FAILURE = 'LOAD_DATABASE_LIST_FAILURE';
export const LOAD_DATABASE_DATA_SUCCESS = 'LOAD_DATABASE_DATA_SUCCESS';
export const LOAD_DATABASE_DATA_FAILURE = 'LOAD_DATABASE_DATA_FAILURE';