// Add action types here

export const SAVE_PHONE = 'SAVE_PHONE';
export const SEND_CODE_STARTED = 'SEND_CODE_STARTED';
export const SEND_CODE_SUCCESS = 'SEND_CODE_SUCCESS';
export const SEND_CODE_FAILURE = 'SEND_CODE_FAILURE';
export const VERIFY_CODE_STARTED = 'VERIFY_CODE_STARTED';
export const VERIFY_CODE_SUCCESS = 'VERIFY_CODE_SUCCESS';
export const VERIFY_CODE_FAILURE = 'VERIFY_CODE_FAILURE';
export const SAVE_NAME = 'SAVE_NAME';
export const SAVE_USER_STARTED = 'SAVE_USER_STARTED';
export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS';
export const SAVE_USER_FAILURE = 'SAVE_USER_FAILURE';
export const SAVE_DRIVING_STARTED = 'SAVE_DRIVING_STARTED';
export const SAVE_DRIVING_SUCCESS = 'SAVE_DRIVING_SUCCESS';
export const SAVE_DRIVING_FAILURE = 'SAVE_DRIVING_FAILURE';
export const SAVE_IMAGE_STARTED = 'SAVE_IMAGE_STARTED'; 
export const SAVE_IMAGE_SUCCESS = 'SAVE_IMAGE_SUCCESS'; 
export const SAVE_IMAGE_FAILURE = 'SAVE_IMAGE_FAILURE'; 





