export const LOAD_ADDRESSES_STARTED = 'LOAD_ADDRESSES_STARTED';
export const LOAD_ADDRESSES_SUCCESS = 'LOAD_ADDRESSES_SUCCESS';
export const LOAD_ADDRESSES_FAILURE = 'LOAD_ADDRESSES_FAILURE';
export const SAVE_ADDRESS_STARTED = 'SAVE_ADDRESS_STARTED';
export const SAVE_ADDRESS_SUCCESS = 'SAVE_ADDRESS_SUCCESS';
export const SAVE_ADDRESS_FAILURE = 'SAVE_ADDRESS_FAILURE';
